[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  APP_ENV = "production"

[context.branch-deploy.environment]
  APP_ENV = "development"
  EMAIL_ALLOWLIST = "obsidianhexer@proton.me"

[context.deploy-preview.environment]
  APP_ENV = "development"
  EMAIL_ALLOWLIST = "obsidianhexer@proton.me"

[context.dev.environment]
  APP_ENV = "development"
  EMAIL_ALLOWLIST = "obsidianhexer@proton.me"
